Fixing checkstyle issues.
Catching raw Exception causes the following checkylist
error: Catching 'Exception' is not allowed. [IllegalCatch]

Bug: 149600887
Test: atest CarServiceUnitTest
Change-Id: I402090df07fe425c3d441fa7cfe349a31a290879