Avoid catching raw Exception in CarPropertyManager.
Catching raw Exception causes the following checkylist
error: CarPropertyManager.java:179:11: Catching 'Exception' is not allowed. [IllegalCatch]

Bug: 149600887
Test: atest CarServiceUnitTest
Change-Id: Ic81c860506215d6d80f099968bbdd2f80cb0f7ca